### ISSUE TITLE
Any documentation ?

### ISSUE THREAD

**Issue by guizmaii** [rgeo/activerecord-mysql2spatial-adapter#16]
Hi,

Is there any documentation somewhere ?
The link in the README is dead.

**Comment by benatkin** [comment]
I think that link was just to the rdoc. Those are available for any gem here: http://www.rubydoc.info/gems/activerecord-mysql2spatial-adapter

**Comment by januszm** [comment]
I fixed the Readme file with the update today.

**Comment by guizmaii** [comment]
Thanks
