### ISSUE TITLE
ActiveRecord 4.0

### ISSUE THREAD

**Issue by michaelcham** [rgeo/activerecord-mysql2spatial-adapter#18]
Does this only work with ActiveRecord 4?  So Rails 4? Anyway to work for Rails 3?

**Comment by januszm** [comment]
Just use previous version for Rails 3 , AFAIR 0.4.x. It works pretty well, with the exception for schema dumps in Ruby format.

**Comment by januszm** [comment]
I'll try to test my recent changes with ActiveRecord 3.x , ie. ```def indexes``` and ColumnMethods

**Comment by januszm** [comment]
@michaelcham For Rails 3 please use earlier versions of the gem, eg. the last 0.4.x version
