### ISSUE TITLE
Specifying spatial types in test fixtures

### ISSUE THREAD

**Issue by haxney** [rgeo/activerecord-mysql2spatial-adapter#2]
Having looked at the documentation and code for a bit, I can't figure out a way to specify geometry types in Rails YAML fixtures. Is there a way to do this, either by specifying the attributes directly with something like

``` yaml
model:
  pos: !ruby/object:Point
    x: 1
    y: 1
```

or by using WKT like this:

``` yaml
model:
  pos: POINT(1 1)
```

If there isn't already a way to do this, consider this a feature request for such functionality. I would be willing to help write the necessary code if given some pointers.

**Comment by januszm** [comment]
@haxney @tetsutan is this still an issue or should we close it?

**Comment by tetsutan** [comment]
No problem. Thanks.
